<script setup lang="ts">
import BVClinicianShell from '../components/BVClinicianShell.vue'
import type { SessionResults } from '../types/session'
defineProps<{ results: SessionResults }>()
defineEmits<{ done: [] }>()
</script>

<template>
  <BVClinicianShell active-sidebar-item="results" subtitle="Session Summary"><div class="p-6 max-w-5xl"><div class="flex justify-between items-start mb-6"><div><h1 class="text-2xl font-semibold text-gray-800">Session Summary</h1><p class="text-sm text-gray-500 mt-1">Colourful Semantics · {{ results.config.exerciseCount }} activities</p></div><div class="flex gap-2"><span class="bg-orange-100 text-orange-700 px-3 py-1 rounded-full text-xs font-bold">WHO</span><span class="bg-yellow-100 text-yellow-700 px-3 py-1 rounded-full text-xs font-bold">DOING</span><span class="bg-green-100 text-green-700 px-3 py-1 rounded-full text-xs font-bold">WHAT</span></div></div><div class="grid md:grid-cols-3 gap-4 mb-6"><div class="bg-white border rounded-xl p-4 text-center"><b class="block text-2xl">{{ results.exercises.filter(Boolean).length }} / {{ results.config.exerciseCount }}</b><span class="text-xs text-gray-500">Activities completed</span></div><div class="bg-white border rounded-xl p-4 text-center"><b class="block text-2xl">{{ results.exercises.flatMap(e => e ? [e.who,e.doing,e.what] : []).reduce((n,r) => n + r.hintsUsed, 0) }}</b><span class="text-xs text-gray-500">Hints used</span></div><div class="bg-white border rounded-xl p-4 text-center"><b class="block text-2xl">{{ results.exercises.flatMap(e => e ? [e.who,e.doing,e.what] : []).filter(r => r.isSemanticAlt).length }}</b><span class="text-xs text-gray-500">Semantic alternatives</span></div></div><div class="bg-white border rounded-xl overflow-hidden mb-6"><div class="bg-[#1e3a28] text-white text-xs font-bold uppercase tracking-widest px-4 py-3">Detailed results</div><div v-for="exercise in results.exercises.filter(Boolean)" :key="exercise.exerciseNumber" class="p-4 border-b last:border-0"><div class="text-xs text-gray-400 mb-1">Exercise {{ exercise.exerciseNumber }}</div><div class="font-semibold text-gray-800">{{ exercise.sentenceProduced }}</div></div></div><button @click="$emit('done')" class="bg-purple-600 text-white font-bold px-6 py-3 rounded-xl">Return to main menu</button></div></BVClinicianShell>
</template>
